#!/bin/bash
#README: This script sets the username and password to use for a single shell session of mssql-conf.
#Run this script as "source mssql-conf-credentials" or ". mssql-conf-credentials" if you don't want mssql-conf to remember your credentials

echo -n "Enter your SQL Server Username and press [ENTER]: "
read USERNAME
echo -n "Enter your SQL Server Password and press [ENTER]: "
read -s PASSWORD
echo
export MSSQL_CONF_USERNAME="$USERNAME"
export MSSQL_CONF_PASSWORD="$PASSWORD"